spring:
  application:
    name: bulgarianmountains

  data:
    mongodb:
      uri: mongodb://${MONGO_DB_USERNAME}:${MONGO_DB_PASSWORD}@localhost:27017/${MONGO_DB_DATABASE}?authSource=${MONGO_DB_DATABASE}

logging:
  file:
    name: logging
  level:
    root: warn
    org:
      springframework:

        data:
          mongodb: debug
        web: debug